"""
Django settings for travel_ticket_system project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-m%v1-p)ho9xx25&g!&&skaa+x!g!v9rg(n=p-rr4a^=ttxxz^-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# HTTPS配置
SECURE_SSL_REDIRECT = not DEBUG  # 仅在生产环境重定向所有HTTP请求到HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # 支持代理服务器的HTTPS
SECURE_HSTS_SECONDS = 3600  # 1小时的HSTS策略
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG  # 仅在生产环境启用子域名HTTPS
SECURE_HSTS_PRELOAD = not DEBUG  # 仅在生产环境允许浏览器预加载HSTS策略
SECURE_BROWSER_XSS_FILTER = True  # 启用XSS防护
SECURE_CONTENT_TYPE_NOSNIFF = True  # 防止浏览器猜测内容类型
SECURE_REFERRER_POLICY = 'same-origin'  # 安全的Referer策略

# 安全Cookie设置
CSRF_COOKIE_SECURE = not DEBUG  # 仅在生产环境使用HTTPS传输CSRF Cookie
SESSION_COOKIE_SECURE = not DEBUG  # 仅在生产环境使用HTTPS传输Session Cookie

# 静态文件和媒体文件URL配置
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

# 确保在生产环境中使用HTTPS URL
if not DEBUG:
    STATIC_URL = 'https://' + ALLOWED_HOSTS[0] + '/static/'
    MEDIA_URL = 'https://' + ALLOWED_HOSTS[0] + '/media/'

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django_extensions',
    'ticket.apps.TicketConfig',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "travel_ticket_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "travel_ticket_system.wsgi.application"
# 跨域设置
CORS_ORIGIN_ALLOW_ALL = True

# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 自定义用户模型
AUTH_USER_MODEL = 'ticket.User'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'travel_ticket_system',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# 静态文件目录配置，用于开发环境
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfiles'),
]
