# Generated by Django 6.0 on 2026-02-02 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="用户名"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[(0, "游客"), (1, "景点管理员"), (2, "网站管理员")],
                        default=0,
                        verbose_name="角色",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="头像"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("", "请选择性别"),
                            ("male", "男"),
                            ("female", "女"),
                            ("other", "其他"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                (
                    "reset_token",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="重置密码token",
                    ),
                ),
                (
                    "reset_token_expiry",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="重置密码token过期时间"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="分类描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "景点分类",
                "verbose_name_plural": "景点分类",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="资讯标题")),
                ("content", models.TextField(verbose_name="资讯内容")),
                (
                    "is_announcement",
                    models.BooleanField(default=False, verbose_name="是否为公告"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/",
                        verbose_name="资讯图片",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "资讯公告",
                "verbose_name_plural": "资讯公告",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="地区名称"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "地区信息",
                "verbose_name_plural": "地区信息",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScenicSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_id", models.IntegerField(default=0, verbose_name="显示ID")),
                (
                    "category",
                    models.CharField(
                        default="自然风光类", max_length=50, verbose_name="分类"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="景点名称")),
                ("description", models.TextField(verbose_name="景点描述")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="门票价格"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="scenic_spots/", verbose_name="景点图片"
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="景点地址")),
                (
                    "opening_hours",
                    models.CharField(max_length=100, verbose_name="开放时间"),
                ),
                ("is_hot", models.BooleanField(default=False, verbose_name="是否热门")),
                (
                    "tags",
                    models.CharField(
                        default="热门",
                        help_text="多个标签用逗号分隔",
                        max_length=100,
                        verbose_name="标签",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1, default=0.0, max_digits=3, verbose_name="评分"
                    ),
                ),
                (
                    "booking_count",
                    models.IntegerField(default=0, verbose_name="预约人数"),
                ),
                (
                    "total_tickets",
                    models.IntegerField(default=1000, verbose_name="总票数"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否上架"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_scenic_spots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="景点管理员",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ticket.region",
                        verbose_name="地区",
                    ),
                ),
            ],
            options={
                "verbose_name": "景点信息",
                "verbose_name_plural": "景点信息",
            },
        ),
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="carousel/", verbose_name="轮播图片"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="轮播顺序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "scenic_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.scenicspot",
                        verbose_name="关联景点",
                    ),
                ),
            ],
            options={
                "verbose_name": "轮播图",
                "verbose_name_plural": "轮播图",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BrowseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "browse_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="浏览时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "scenic_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.scenicspot",
                        verbose_name="景点",
                    ),
                ),
            ],
            options={
                "verbose_name": "浏览历史",
                "verbose_name_plural": "浏览历史",
                "ordering": ["-browse_time"],
            },
        ),
        migrations.CreateModel(
            name="ScenicSpotComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="留言内容")),
                (
                    "reply",
                    models.TextField(blank=True, null=True, verbose_name="回复内容"),
                ),
                (
                    "reply_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="回复时间"
                    ),
                ),
                (
                    "is_replied",
                    models.BooleanField(default=False, verbose_name="是否回复"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "scenic_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.scenicspot",
                        verbose_name="景点",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "景点留言",
                "verbose_name_plural": "景点留言",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="门票名称")),
                (
                    "type",
                    models.CharField(
                        choices=[("single", "单票"), ("package", "套票")],
                        default="single",
                        max_length=20,
                        verbose_name="门票类型",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="门票价格"
                    ),
                ),
                ("stock", models.IntegerField(default=1000, verbose_name="默认库存")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="前缀"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "scenic_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.scenicspot",
                        verbose_name="景点",
                    ),
                ),
            ],
            options={
                "verbose_name": "门票类型",
                "verbose_name_plural": "门票类型",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "use_date",
                    models.DateField(blank=True, null=True, verbose_name="使用日期"),
                ),
                ("quantity", models.IntegerField(verbose_name="数量")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="总价"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "待支付"),
                            (1, "已支付"),
                            (2, "已取消"),
                            (3, "已使用"),
                            (4, "已退款"),
                            (5, "退款审核中"),
                        ],
                        default=0,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=50, unique=True, verbose_name="订单号"),
                ),
                (
                    "refund_reason",
                    models.TextField(blank=True, null=True, verbose_name="退款原因"),
                ),
                (
                    "refund_apply_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="退款申请时间"
                    ),
                ),
                (
                    "refund_audit_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="退款审核时间"
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="退款金额",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "scenic_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.scenicspot",
                        verbose_name="景点",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.tickettype",
                        verbose_name="门票类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "scenic_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.scenicspot",
                        verbose_name="景点",
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏记录",
                "verbose_name_plural": "收藏记录",
                "ordering": ["-created_at"],
                "unique_together": {("user", "scenic_spot")},
            },
        ),
        migrations.CreateModel(
            name="DateStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("use_date", models.DateField(verbose_name="使用日期")),
                ("stock", models.IntegerField(default=1000, verbose_name="当天库存")),
                ("sold", models.IntegerField(default=0, verbose_name="当天已售")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.tickettype",
                        verbose_name="门票类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "日期库存",
                "verbose_name_plural": "日期库存",
                "ordering": ["use_date"],
                "unique_together": {("ticket_type", "use_date")},
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "use_date",
                    models.DateField(blank=True, null=True, verbose_name="使用日期"),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="数量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "scenic_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.scenicspot",
                        verbose_name="景点",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.tickettype",
                        verbose_name="门票类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "购物车",
                "verbose_name_plural": "购物车",
                "unique_together": {("user", "scenic_spot", "ticket_type", "use_date")},
            },
        ),
    ]
