# Generated by Django 6.0 on 2025-12-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenicspot",
            name="category",
            field=models.CharField(
                choices=[
                    ("natural", "自然风光类"),
                    ("historical", "历史遗迹类"),
                    ("folklore", "民俗文化类"),
                    ("modern", "现代都市类"),
                    ("leisure", "休闲度假类"),
                    ("theme", "主题乐园类"),
                    ("religious", "宗教文化类"),
                    ("rural", "农业乡村类"),
                ],
                default="natural",
                max_length=20,
                verbose_name="分类",
            ),
        ),
        migrations.AddField(
            model_name="scenicspot",
            name="region",
            field=models.CharField(default="全国", max_length=50, verbose_name="地区"),
        ),
        migrations.AddField(
            model_name="scenicspot",
            name="tags",
            field=models.CharField(
                default="热门",
                help_text="多个标签用逗号分隔",
                max_length=100,
                verbose_name="标签",
            ),
        ),
    ]
