# Generated by Django 6.0 on 2026-03-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="支付方式"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_serial",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="支付流水号"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="支付时间"),
        ),
    ]
