# Generated by Django 6.0 on 2025-12-20 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_scenicspot_category_scenicspot_region_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="scenicspot",
            name="booking_count",
            field=models.IntegerField(default=0, verbose_name="预约人数"),
        ),
        migrations.AddField(
            model_name="scenicspot",
            name="rating",
            field=models.DecimalField(
                decimal_places=1, default=0.0, max_digits=3, verbose_name="评分"
            ),
        ),
        migrations.AddField(
            model_name="scenicspot",
            name="total_tickets",
            field=models.IntegerField(default=1000, verbose_name="总票数"),
        ),
        migrations.CreateModel(
            name="ScenicSpotComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="留言内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "scenic_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.scenicspot",
                        verbose_name="景点",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "景点留言",
                "verbose_name_plural": "景点留言",
                "ordering": ["-created_at"],
            },
        ),
    ]
