# Generated by Django 6.0 on 2025-12-20 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0003_alter_user_managers_scenicspot_booking_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="use_date",
            field=models.DateField(blank=True, null=True, verbose_name="使用日期"),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="退款金额",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_apply_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="退款申请时间"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_audit_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="退款审核时间"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_reason",
            field=models.TextField(blank=True, null=True, verbose_name="退款原因"),
        ),
        migrations.AddField(
            model_name="order",
            name="use_date",
            field=models.DateField(blank=True, null=True, verbose_name="使用日期"),
        ),
        migrations.AddField(
            model_name="scenicspotcomment",
            name="is_replied",
            field=models.BooleanField(default=False, verbose_name="是否回复"),
        ),
        migrations.AddField(
            model_name="scenicspotcomment",
            name="reply",
            field=models.TextField(blank=True, null=True, verbose_name="回复内容"),
        ),
        migrations.AddField(
            model_name="scenicspotcomment",
            name="reply_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="回复时间"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "待支付"),
                    (1, "已支付"),
                    (2, "已取消"),
                    (3, "已使用"),
                    (4, "已退款"),
                ],
                default=0,
                verbose_name="订单状态",
            ),
        ),
        migrations.CreateModel(
            name="BrowseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "browse_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="浏览时间"),
                ),
                (
                    "scenic_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.scenicspot",
                        verbose_name="景点",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "浏览历史",
                "verbose_name_plural": "浏览历史",
                "ordering": ["-browse_time"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="地区名称"
                    ),
                ),
                ("level", models.IntegerField(default=1, verbose_name="地区级别")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ticket.region",
                        verbose_name="父地区",
                    ),
                ),
            ],
            options={
                "verbose_name": "地区信息",
                "verbose_name_plural": "地区信息",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="门票名称")),
                (
                    "type",
                    models.CharField(
                        choices=[("single", "单票"), ("package", "套票")],
                        default="single",
                        max_length=20,
                        verbose_name="门票类型",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="门票价格"
                    ),
                ),
                ("stock", models.IntegerField(default=1000, verbose_name="库存数量")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "scenic_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.scenicspot",
                        verbose_name="景点",
                    ),
                ),
            ],
            options={
                "verbose_name": "门票类型",
                "verbose_name_plural": "门票类型",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="cart",
            name="ticket_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ticket.tickettype",
                verbose_name="门票类型",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="ticket_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ticket.tickettype",
                verbose_name="门票类型",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together={("user", "scenic_spot", "ticket_type", "use_date")},
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "scenic_spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ticket.scenicspot",
                        verbose_name="景点",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏记录",
                "verbose_name_plural": "收藏记录",
                "ordering": ["-created_at"],
                "unique_together": {("user", "scenic_spot")},
            },
        ),
    ]
