# Generated by Django 6.0 on 2025-12-20 05:00

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0004_cart_use_date_order_refund_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="birthdate",
            field=models.DateField(blank=True, null=True, verbose_name="出生日期"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("", "请选择性别"),
                    ("male", "男"),
                    ("female", "女"),
                    ("other", "其他"),
                ],
                default="",
                max_length=10,
                verbose_name="性别",
            ),
        ),
    ]
