# Generated by Django 6.0 on 2025-12-20 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0005_alter_user_managers_user_birthdate_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenicspot",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_scenic_spots",
                to=settings.AUTH_USER_MODEL,
                verbose_name="景点管理员",
            ),
        ),
    ]
