# Generated by Django 6.0 on 2025-12-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0007_category_alter_scenicspot_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenicspot",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否上架"),
        ),
    ]
