# Generated by Django 6.0 on 2025-12-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0008_scenicspot_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "待支付"),
                    (1, "已支付"),
                    (2, "已取消"),
                    (3, "已使用"),
                    (4, "已退款"),
                    (5, "退款审核中"),
                ],
                default=0,
                verbose_name="订单状态",
            ),
        ),
    ]
