# Generated by Django 6.0 on 2025-12-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0009_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenicspot",
            name="category",
            field=models.CharField(
                default="自然风光类", max_length=50, verbose_name="分类"
            ),
        ),
    ]
