# Generated by Django 6.0 on 2025-12-26 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0010_alter_scenicspot_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenicspot",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ticket.region",
                verbose_name="地区",
            ),
        ),
    ]
