# Generated by Django 6.0 on 2025-12-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0011_alter_scenicspot_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenicspot",
            name="display_id",
            field=models.IntegerField(default=0, verbose_name="显示ID"),
        ),
    ]
